let productos = [
    {
        id: 1,
        nombre: "Café Kobe",
        descripcion: "Café solo, es habitual el uso de café de la variante arábiga. Habitualmente suele tener algo de espuma por encima.",
        precio: 1500,
        img: "https://imageup.me/images/97300b09-a1d9-4c83-9ec7-5c8a9d356513.png",
        cantidad: 1,
    },
    {
        id: 2,
        nombre: "Café Lebron",
        descripcion: "Café Lebron comúnmente conocido como café cortado o macchiato, este tipo de café es uno de los más demandados.",
        precio: 1250,
        img: "https://imageup.me/images/4fe393e4-e7a6-4057-90de-60308f6cf16c.png",
        cantidad: 1,
    },
    {
        id: 3,
        nombre: "Café Ginobilli",
        descripcion: "El Ginobilli lungo o largo se trata de un tipo de café en el que la extracción de agua en contacto con los granos de café molidos se realiza de manera más prolongada, lo que conlleva más cantidad de infusión.",
        precio: 1000,
        img: "https://imageup.me/images/c633c758-7aaf-40d6-ba22-249d8d16ac67.png",
        cantidad: 1,
    },
    {
        id: 4,
        nombre: "Café Antetokounmpo",
        descripcion: "Café expreso como base un cuarto de nuestra taza de café o vaso alto. ",
        precio: 900,
        img: "https://imageup.me/images/1edb3d72-1754-48d5-adfc-92c3f2da3ce8.png",
        cantidad: 1,
    },
    {
        id: 5,
        nombre: "Café Luka",
        descripcion: "Café Luka, una proporción muy semejante de leche y café, 50%y  50%, aproximadamente.",
        precio: 800,
        img: "https://imageup.me/images/d642e126-d1fd-4b40-afe7-88d0233360cf.png",
        cantidad: 1,
    },
    {
        id: 6,
        nombre: "Café Shaq",
        descripcion: "Cafe Shaq, gran parte de Chocolate y cacao.",
        precio: 600,
        img: "https://imageup.me/images/b328a4bd-c1f7-44cc-aca1-03d17588debd.png",
        cantidad: 1,
    },
    {
        id: 7,
        nombre: "Café Morant",
        descripcion: "El café Morant es una bebida más dulce del café y  leche condensada.",
        precio: 550,
        img: "https://imageup.me/images/cb8675c9-5c2f-4973-a555-42a5e307be9a.png",
        cantidad: 1,
    },
];